version: '3.8'

services:

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./sql/populate.sql:/docker-entrypoint-initdb.d/populate.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=store

  minio:
    image: minio/minio
    command: server --console-address ":9001" /data
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-storage:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=pass7890

  mc:
    image: minio/mc:latest
    depends_on:
     - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 admin pass7890;
      /usr/bin/mc rb --force local/images/;
      /usr/bin/mc mb --quiet local/images/;
      /usr/bin/mc anonymous set public local/images;
      /usr/bin/mc cp /tmp/images/*.jpg local/images;
      "
    volumes:
      - ./data:/tmp

  backend:
    build: ./backend
    environment:
      - DB_SERVER=postgres
      - MINIO_URL=http://minio:9000
    ports:
      - 8080:8080
    depends_on:
      - postgres
      - minio
    links:
      - postgres
  
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend

volumes:
  postgres-db:
  minio-storage: